#!/usr/bin/env bash
# shellcheck disable=SC2317,SC2059

#--- [ STRICT MODE ] -----------------------------------------------------------

# Set strict mode for safer script execution.
set -o errexit   # Exit on command error.
set -o errtrace  # Trap errors in functions and sub-shells.
set -o nounset   # Exit on uninitialized variables.
set -o pipefail  # Use the error status of the first failed command in a pipeline.

# Set Internal Field Separator to newline and tab to handle file names with spaces properly.
IFS=$'\n\t'

#--- [ GLOBALS ] ---------------------------------------------------------------

readonly col_reset="\x1b[0m"       # Text Reset
readonly col_green="\x1b[32m"     # Green
readonly col_yellow="\x1b[33m"    # Yellow
readonly col_red="\x1b[31m"       # Red
readonly char_succ="✔"            # Success character
readonly char_fail="✖"            # Failure character

# Function to display a spinner while another command is executing.
spinner() {
    local i=0
    local sp="\|/-"
    local n=${#sp}
    while ps a | awk '{print $1}' | grep -q "${1}"; do
        sleep "0.75"
        printf "%s\b" "${sp:i++%n:1}"  # Display next spinner character.
    done
}

error() { printf "${col_red}${char_fail}${col_reset}"; }# Function to display an error.
ok() { printf "${col_green}${char_succ}${col_reset}"; }# Function to display a success message.

#--- [ MAIN SCRIPT ] -----------------------------------------------------------

# Print header.
printf "\n\n================================================================================\n"
printf "=                         Installing MAS packages...                           =\n"
printf "================================================================================\n"

# Prompt for sudo password at the start.
sudo -v

# Refresh sudo timestamp to prevent multiple password prompts.
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# Check if mas is installed
if ! command -v mas &> /dev/null; then
    printf "\n\n${col_yellow}MAS not found! Installing via Homebrew...${col_reset}\n"
	brew install mas
fi

# Install from Mac App Store
printf "\n\n${col_yellow}Installing Mac App Store apps${col_reset}"

# Install Apps from the MAS INSTALLS section
# Extracting commands using grep and executing them
while IFS= read -r line; do
    printf "\n ⇒ %s " "$line"
    eval "$line" >/dev/null 2>&1 & spinner "$!"
    ok
done < <(grep --color=never -A9999 '### MAS PACKAGES ###' "$0" | grep --color=never '^mas install')

printf "\n\n${col_yellow}All installations complete!${col_reset}\n"

exit 0

### MAS PACKAGES ###
mas install 1295203466 # "Microsoft Remote Desktop"
mas install 937984704  # "Amphetamine"