#!/usr/bin/env bash

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until `.brew` has finished
while true; do
	sudo -n true
	sleep 60
	kill -0 "$$" || exit
done 2>/dev/null &

# Make sure we’re using the latest Homebrew.
brew update

# Upgrade any already-installed formulae.
brew upgrade

# Save Homebrew’s installed location.
BREW_PREFIX=$(brew --prefix)

# Taps
#tap 'homebrew/cask'
#tap 'homebrew/cask-eid'
#tap 'homebrew/cask-fonts'
#tap 'homebrew/cask-versions'
#tap 'homebrew/bundle'

# Install Java first to prevent packages that depends on it from failing
brew cask install 'adoptopenjdk'

# Install GNU core utilities (those that come with OS X are outdated)
brew install 'coreutils'
brew install 'moreutils'
brew install 'findutils'
brew install 'gnu-sed'

# Install a modern version of Bash.
brew install 'bash'
brew install 'bash-completion2'

# Install wget with IRI support
brew install 'wget'

# Install more recent versions of some OS X tools
brew install 'vim'
brew install 'nano'
brew install 'grep'
brew install 'openssh'
brew install 'screen'
brew install 'gmp'

# Install other useful binaries
brew install 'the_silver_searcher'
brew install 'fzf'
brew install 'git'
brew install 'git-lfs'
brew install 'gnupg'
brew install 'hub'
brew install 'ghostscript' # Also known as 'sg'
brew install 'pipeviewer'  # Also known as 'pv'
brew install 'rename'
brew install 'tree' # List directories in a tree structure
brew install 'zopfli'
brew install 'zlib' # Needed for Memcached
brew install 'p7zip'
brew install 'pigz'
brew install 'vbindiff'
brew install 'httpie'
brew install 'bat' # "cat" on steroids
brew install 'terminal-notifier'
brew install 'pidcat' # colored logcat guy
brew install 'ncdu'   # Find where your diskspace went
brew install 'shfmt' # Autoformat shell script source code

# Install multimedia tools
brew install 'ffmpeg'
brew install 'imagemagick'

# Install Mac App Store command-line interface
brew install 'mas'

# Install some CTF tools;
brew install 'aircrack-ng' #Java 1.8+ is required to install this forumula
brew install 'binutils'
brew install 'binwalk'
brew install 'cifer'
brew install 'dex2jar'
brew install 'dns2tcp'
brew install 'fcrackzip'
brew install 'foremost'
brew install 'hashpump'
brew install 'hydra'
brew install 'john'
brew install 'knock'
brew install 'netpbm'
brew install 'nmap'
brew install 'pngcheck'
brew install 'socat'
brew install 'sqlmap'
brew install 'tcpflow'
brew install 'tcpreplay'
brew install 'tcptrace'
brew install 'ucspi-tcp' # `tcpserver` etc.
brew install 'xpdf'
brew install 'xz'

# Install some Forensic tools
brew install 'autopsy' #"java is required
brew install 'dc3dd'
brew install 'volatility'

# Apps
brew cask install 'atom'
brew cask install 'adobe-creative-cloud'
brew cask install 'adobe-acrobat-reader'
brew cask install 'betterzip'
brew cask install 'db-browser-for-sqlite'
brew cask install 'dropbox'
brew cask install 'docker'
brew cask install 'easyfind'
brew cask install 'Cyberduck'
brew cask install 'fsmonitor'
brew cask install 'ghidra' # requires java 11+
brew cask install 'github'
brew cask install 'gpg-suite'
brew cask install 'insomnia'
brew cask install 'mysqlworkbench'
brew cask install 'maltego'
brew cask install 'microsoft-office'
brew cask install 'skype'
brew cask install 'slack'
brew cask install 'transmission'
brew cask install 'vagrant'
brew cask install 'viscosity'
brew cask install 'vmware-fusion'
brew cask install 'wireshark'
brew cask install 'virtualbox' # Might need to allow access in Security settings
brew cask install 'virtualbox-extension-pack'
brew cask install 'vlc'
brew cask install 'yed'
brew cask install 'android-platform-tools'

# Browsers
brew cask install 'google-chrome'
# brew cask install 'google-chrome-canary'
brew cask install 'firefox'
# brew cask install 'firefoxnightly'
# brew cask install 'webkit-nightly'
# brew cask install 'chromium'
brew cask install 'tor-browser'
brew cask install 'brave-browser'

# Quicklook
brew cask install 'qlcolorcode'
brew cask install 'qlmarkdown'
brew cask install 'quicklook-json'
brew cask install 'quicklook-csv'
brew cask install 'qlstephen'
brew cask install 'qlvideo'
brew cask install 'suspicious-package'
brew cask install 'qlprettypatch'
brew cask install 'WebPQuickLook'
brew cask install 'qlswift'
brew cask install 'betterzip'

# zsh
brew install zsh-autosuggestions
brew install zsh-completions
brew install zsh-syntax-highlighting

# Fonts
brew cask install 'font-hack-nerd-font'

# Remove outdated versions from the cellar
brew cleanup

# Mac App Store
mas install 442160987 #'Flycut'
mas install 638161122 #'YubiKey Personalization Tool'
mas install 509733654 #'HashMaker'
mas install 1295203466 #'Microsoft Remote Desktop'
mas install 937984704 #'Amphetamine'
mas install 404010395 #'TextWrangler'

# Atom packages
apm install compare-files
apm install atom-beautify
apm install github-atom-light-syntax
apm install ide-json
apm install minimap
apm install minimap-find-and-replace
apm install minimap-split-diff
apm install split-diff
